### ISSUE TITLE
 Columns moved

### ISSUE THREAD

**Issue by crpradio** [sverhagen/mp3-browser#64]
See screenshot

![screenshot-mp3browser](https://cloud.githubusercontent.com/assets/600632/10826275/41fed1a6-7e69-11e5-90a7-70dca04f7b3d.PNG)

**Comment by ahmeds833** [comment]
I'm facing the same problem

**Comment by inter-web** [comment]
I have same problem with the tables, anybody say me how fix ?

![celdas-movidas](https://cloud.githubusercontent.com/assets/15849220/11165023/53577b18-8ac8-11e5-9b86-e5fd3f593a2d.jpg)

Thank You very much in advanced!

**Comment by ahmeds833** [comment]
I found it. 

The problem was in class "row" at the following file:
plugins/content/mp3browser/html/HtmlTable.php

Do the following to solve the problem:
1- Open the file Above.
2- go to line 26 and change it from  
	$this->addHtmlLine("<tr class=\"row alternate\">"); 
   to
	 $this->addHtmlLine("<tr class=\"alternate\">");
3- go to line 28 and change it from
	$this->addHtmlLine("<tr class=\"row\">"); 
    to
	$this->addHtmlLine("<tr>"); 
4- go to line 86 and change any attribute of table.

5- to control the apperance of title row, just add class ".mp3browser thead tr" to your CSS file and change it as you want.

**Comment by inter-web** [comment]
I found the solution that published anybody....

![template_css](https://cloud.githubusercontent.com/assets/15849220/11259024/ebd50884-8e23-11e5-8ebd-df4fddf9b436.jpg)
![mp3-browser](https://cloud.githubusercontent.com/assets/15849220/11259023/ebd324b0-8e23-11e5-94a0-216f14d06d39.jpg)

it´s more simple and for me work very fine, I hope can help us

/* fix for mp3 browser table */
.row:before, .row:after {
  content: none !important;
}

José Luis Rosales - México City

**Comment by sverhagen** [comment]
It's probably indeed the solution as @inter-web describes and it's documented [here](https://www.totaalsoftware.com/products/mp3-browser/documentation/147-bootstrap-issue).

It's fixed in a recent commit, but that's not released yet.
