### ISSUE TITLE
Mp3 player works in articles, not in detailed view of product in Virtuemart

### ISSUE THREAD

**Issue by pdvmedia** [sverhagen/mp3-browser#69]
hello,

The plugin works on Joomla! articles but not in the detailed view of a product in virtuemart. Is there a workaround for?

See: http://boekuusvandewege.nl/index.php/nieuwe-cd-s/funiculli-detail and http://boekuusvandewege.nl/index.php/winkel

Thanks a lot!

Pieter de Visser

**Comment by sverhagen** [comment]
This is a long time ago, but since I'm cleaning out issues: I am not familiar with Virtuemart (nor am I able to spend the time to look into it). I believe we've had people in the past run the plugin inside modules and/or components, but I'm not sure. Maybe #62 and aa47833 can be of help. Solved in 0.4.0 ([released here](https://www.totaalsoftware.com/downloads/mp3-browser)).
